from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (
    List,
    Sponsors,
    Streaming,
    Visualize,
    Detail,
    Edit,
    Attendees,
    CSV,
    Related,
    )


urlpatterns = patterns('',
    url(r'^$',
        List.as_view(),
        name='list',
        ),
    url(r'^(sponsor)/$',
        Sponsors.as_view(),
        name='sponsors',
        ),
    url(r'^(visualize)/$',
        Visualize.as_view(),
        name='visualize',
        ),
    url(r'^(streaming)/(?P<slug>[-_\w]+)/$',
        Streaming.as_view(),
        name='streaming',
        ),
    url(r'^(?P<slug>[-_\w]+)/$',
        Detail.as_view(),
        name='detail',
        ),
    url(r'^(?P<slug>[-_\w]+)/edit$',
        login_required(Edit.as_view()),
        name='edit',
        ),
    url(r'^(?P<slug>[-_\w]+)/attendees$',
        login_required(Attendees.as_view()),
        name='attendees',
        ),
    url(r'^(?P<slug>[-_\w]+)/related$',
        login_required(Related.as_view()),
        name='related',
        ),
    url(r'^(?P<slug>[-_\w]+)/csv$',
        login_required(CSV.as_view()),
        name='export',
        ),
    )
